fname = input("whats your first name?: ")
lname = input("what is your last name?: ")
email = input("what is your email?: ")
phone = input("what is your phone?: ")
job = input("what is your job title?: ")
id = input("what is your ID?: ")  #
print(f"{lname.upper()},{fname} \n{job.title()} \n{id} \n{email.lower()} \n{phone}")
bondfirst = input(f"What is your FIRT name? ").title()
bondlast = input(f"What is your LAST name? ").title()
print(f"My name is {bondlast}, {bondfirst} {bondlast}.")
